readme.md

--dev on composer install is deprecated as dev requirements are now installed by default, should be removed from the instructions to avoid any confusion.

removed --dev from composer install instructions

---

app/database/migrations/2015_04_12_172949_add_indexes_to_tagged_items.php

Should help with load speed of forum "categories", a.k.a. tagged threads.

Add indexes to tagged_items table

---

app/views/articles/index.blade.php
app/views/forum/_index.blade.php
app/views/forum/threads/index.blade.php

Sanitize input parameters using three curly braces.

XSS Vulnerability - Sanitize input parameters

---

app/Lio/ServiceProviders/HashidsServiceProvider.php

As discussed in #217, the `register()` method is more appropriate than `boot()` to register bindings with the container. This change also fixes the registration of the `hashids` alias.

Move Hashids binding to register method & fix alias

---

resources/views/forum/threads/show.blade.php

- This PR adds the option to sign in at the thread's bottom if the user is logged out. It looks as follows
- While reading a thread if the reader/user wants to contribute, the immediate instinct is to sign in the fastest way possible and help a co-dev out. 
- It also fixes a small typo: `endif` to `endcan`
Open for improvements if needed :)

If applied this commit adds the option to allow the users to sign in from a thread's page.

---

app/Validation/DoesNotContainUrlRule.php
tests/Components/Validation/DoesNotContainUrlRuleTest.php
tests/Feature/ForumTest.php

Addresses #321 
Also, if you look closely at #318, the failure was due to two whitespaces after "JSON".
Currently, the way the subject is checked DoesNotContainUrlRule is that the subject is "exploded" into an array, then each element is checked via:
```php
$validator->make(['word' => $value], ['word' => 'url'])->passes();
```
if the loop completes, with each element failing the 'url' check, then the custom rule passes.
The problem is that if there is more than one space between words in the subject, some elements of the exploded subject will just be an empty string, which in this case passes ```['word' => 'url']``` validation. This in turn makes the custom rule fail.
Honestly, I think you should consider adding some sanitization to your inputs, then we could avoid this fix. So if you …

Allow multiple spaces between words in subject

---

app/Http/Requests/ThreadRequest.php
resources/views/forum/threads/_form.blade.php
tests/Feature/ForumTest.php

Set the max length of the subject to 60

---

app/Http/Kernel.php
app/Http/Middleware/TrustProxies.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
config/app.php
config/broadcasting.php
config/cache.php
config/filesystems.php
config/hashing.php
config/logging.php
config/queue.php
config/session.php
package.json
tests/CreatesApplication.php
yarn.lock

This pull request includes the changes for upgrading to Laravel 5.6. Feel free to commit any additional changes to the `shift-6274` branch.
**Before merging**, you should:
- Checkout the `shift-6274` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.6
- Run `composer update` (if the pre-scripts fail, add `--no-scripts`)
- Thoroughly test your application
If you need help with your upgrade, check out the [Shift Human Services](https://laravelshift.com/human-services) or join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack room to get answers to all your Laravel questions.

Laravel 5.6 Shift

---

resources/views/errors/403.blade.php
resources/views/errors/404.blade.php
resources/views/errors/500.blade.php

We could do something fun with these later down the line, but I think they work for now

Style error pages

---

resources/js/components/MultiSelect.vue
resources/views/forum/threads/_form.blade.php

This PR updates the multiselect to use a `<select>` element under the hood instead of hidden inputs.
This is better for accessibility and has the added bonus of fixing the broken tests.

swap hidden input for select

---

resources/css/threads.css

Wrap text which overlaps container 

---

app/Models/Thread.php
resources/views/forum/overview.blade.php
resources/views/forum/threads/show.blade.php
tests/Feature/ForumTest.php

This PR resolves #431 
It adds a visual indication on the forum overview page highlighting threads which have been resolved. Clicking `View solution` takes you directly to the accepted answer.

Highlight solved threads on overview

---

resources/views/forum/overview.blade.php

If someone were to add a code snippet such as `{{ $foo }}` and this were output in the excerpt, Vue would interpret this as a valid expression and would throw an error.
Adding the `v-pre` directive tells Vue to ignore anything in the element.

Remove possibility of Vue error

---

app/Http/Livewire/Notifications.php

There is no need to return the unread notification count as the component will re-render after the notification is marked as read.

Prevent duplicate query in notifications component

---

resources/views/forum/threads/_view_solution.blade.php
resources/views/forum/threads/show.blade.php

Closes #495 . Sorry for the problem I caused here, completely forgot tags existed since I didn't have any on my test thread.
Here's a screenshot of what they look like now:
I've moved the solution button to the end too. On mobile, the tags will be directly below the title and the solution button underneath them.

Fix tag misalignment due to solution button

---

app/Http/Controllers/Articles/ArticlesController.php
app/Http/Controllers/Articles/SeriesController.php
app/Http/Requests/ArticleRequest.php
app/Models/Article.php
resources/css/forms.css
resources/js/app.js
resources/views/_partials/_editor.blade.php
resources/views/articles/_form.blade.php
resources/views/articles/create.blade.php
resources/views/articles/show.blade.php
resources/views/series/_form.blade.php
tests/Integration/Jobs/CreateArticleTest.php
tests/Integration/Jobs/UpdateArticleTest.php

This PR makes some subtle changes to inputs and styles:
- Fields repopulate correctly when form validation fails
- Choices select/multi-select field styled more consistently with the rest of the UI
- Markdown editor increases in size as the user types

Format the article editor

---

app/Http/Controllers/Articles/ArticlesController.php
app/Http/Requests/ArticleRequest.php
app/Jobs/CreateArticle.php
app/Jobs/UpdateArticle.php
app/Models/Article.php
database/migrations/2020_04_07_185543_create_community_articles_table.php
resources/css/buttons.css
resources/views/articles/_form.blade.php
resources/views/articles/show.blade.php
tests/Feature/ArticleTest.php
tests/Integration/Jobs/CreateArticleTest.php
tests/Integration/Jobs/UpdateArticleTest.php

This PR adds support for setting the status of an article - draft or published.
I've added a `published_at` field to the `articles` table. If this date is populated, the article is live, if it's null, it's a draft.
There is a dropdown button on the article form which allows the user to choose the status when creating or editing an article.

Add support for draft and published articles

---

app/Http/Controllers/Articles/ArticlesController.php
app/Http/Livewire/ShowArticles.php
app/Models/Article.php
app/Models/Tag.php
resources/css/tags.css
resources/views/articles/index.blade.php
resources/views/livewire/show-articles.blade.php
tests/Feature/ArticleTest.php
tests/Integration/Models/ArticleTest.php

This is the article listing page. It uses Livewire to make sorting and filtering feel fast and dynamic.
Clicking tags either in the sidebar or the ones associated with each artilce will filter the results to that tag.
Recent orders the articles by publish date, popular orders by number of likes and trending orders by number of likes in the last week.

List articles

---

app/Http/Livewire/ShowArticles.php
resources/views/livewire/show-articles.blade.php
resources/views/users/articles.blade.php
tests/Feature/ArticleTest.php

- Resolves #543 
- Resolves #538
- Adds CTA to create articles on the overview page
- Add message when no articles created

Post-launch tidy of articles

---

resources/views/livewire/show-articles.blade.php

Show pinned articles

---

resources/views/forum/threads/show.blade.php

This fixed #560 
I tried to keep it in the same style as the existing link but maybe I missed something.
By default my editor removed white spaces on the end of the line. If wanted I will revert that part.

Change the resend verification link to a reply form with post request.

---

.github/workflows/enlightn.yml
.github/workflows/tests.yml

After some more digging, I found that secrets aren't available to forks even though there is a [proposal under consideration](https://github.community/t/make-secrets-available-to-builds-of-forks/16166).
@driesvints, I'm moving Enlightn to its own workflow. This workflow should run in all scenarios (whether or not secrets are accessible). If secrets are available the Pro package will be pulled in and the bot will be triggered. If not available, the Enlightn CI will be triggered without Pro.
It would be interesting to see that if an owner/maintainer triggers a workflow on a fork, whether that makes secrets available.
Nevertheless, this should be a foolproof way for now. Sorry for all the troubles!

Move Enlightn to own workflow

---

resources/views/layouts/_nav.blade.php

Updates the **Chat > IRC** links to point to the #laravel channel on libera.chat, as the Freenode webchat no longer works.
The switch to `#` instead of its `%23` entity is intentional - Libera's web chat expects a literal hash in channel names and appears to ignore the encoded version entirely.

Move #laravel IRC to libera.chat

---

resources/views/components/articles/summary.blade.php
resources/views/components/threads/summary.blade.php
resources/views/home.blade.php

- Fixes the spacing issue between threads on mobile
- Ensures container heights are consistent regardless of the content inside them

Homepage tweaks

---

app/Models/Article.php
database/seeders/UserSeeder.php
resources/views/components/articles/summary.blade.php

Uses [Unsplash Source](https://source.unsplash.com/) to pull in images for articles. Doing it this way means we only have to store an Unsplash image ID in the database. Unsplash source will get us the image in the required dimensions.
The Unsplash Source website states: 
> Source is built for use in small, low-traffic applications. For production uses, we recommend the official Unsplash API which has more robust features and supports high-traffic use cases.
It doesn't go into detail of what a low-traffic app is. I would prefer to use this over the Unsplash API as we don't need to worry about creating an app and we don't have to make an API call to get the desired image URL. I'm happy to swap this out if preferred.

Use Unsplash images for articles

---

app/Http/Controllers/Articles/ArticlesController.php

Hey!
This PRs only a small one, but it updates something that I just noticed while on the site.
Say if you go to an article, such as https://laravel.io/articles/using-database-transactions-to-write-safer-laravel-code, when you scroll to the bottom to the "Other articles you might like" section, the current article is in the list (the screenshot shows this).
I know that this isn't really a big issue and is probably unlikely to happen often. But, I've made a small PR which _should_ prevent it in the future.
If this is something you might want to pull in, let me know if there are any changes I need to make :smile:

Prevented current article showing in trending articles section

---

resources/views/components/stat-popout.blade.php
tailwind.config.js

Hello 👋🏻 
I came across this issue of that box support only less than 2 digits numbers. So I came up with this solution.

fix: stat popout elements width

---

resources/views/articles/create.blade.php
resources/views/articles/edit.blade.php
resources/views/articles/show.blade.php
resources/views/forum/threads/create.blade.php
resources/views/forum/threads/edit.blade.php
resources/views/forum/threads/show.blade.php
resources/views/layouts/small.blade.php
resources/views/replies/edit.blade.php
resources/views/users/articles.blade.php

Hey!
This fixes #695 . I've added `break-all` because `break-words` did not always break long strings.
Have a great day 😃

Fix #695 - Add word breaks to titles

---

app/Models/User.php

@joedixon
Following #714. I found that we have to rank authors by approved articles.

fix: top authors widget ranking

---

app/Http/Controllers/Auth/GithubController.php

This fixes #689 by passing `true` as second parameter to Auth::login() when logging in using github.

Remember me for GitHub authentication

---

resources/views/components/articles/actions.blade.php

resolves #728
https://user-images.githubusercontent.com/60013703/140835062-41a8434d-4ccb-4e37-ad2d-335653468e0e.mp4

fix article control buttons

---

app/Listeners/SendNewReplyNotification.php
app/Mail/NewReplyEmail.php
app/Notifications/NewReplyNotification.php
resources/views/emails/new_reply.blade.php
tests/Integration/Mail/NewReplyEmailTest.php

New reply email cta

---

database/factories/UserFactory.php
database/seeders/LikeSeeder.php
database/seeders/NotificationSeeder.php
database/seeders/ReplySeeder.php
database/seeders/TagSeeder.php
database/seeders/UserSeeder.php

Hi @driesvints,
This PR is the follow up on https://github.com/laravelio/laravel.io/pull/760 for issue https://github.com/laravelio/laravel.io/issues/677. I took a different approach for the TagSeeder (and LikeSeeder because it is similar and the results are great, see image below). I hope it also works on your side this time.

Improving seeder performance

---

resources/views/articles/show.blade.php

We need to have the flex shrink on the author section in single article. So if the user has a long bio, is not going to stretch like the image below.

add flex-shrink in author image in single article

---

resources/views/home.blade.php

Hello 👋🏻
Here I found an unnecessary scroll in large screen so I switch it to `auto` so the scroll appear only when can be used.

Fix Help Others section scroll

---

resources/views/articles/show.blade.php

Currently, when the browser window is exactly the same width as a responsive breakpoint, the suggested articles list has no padding:
This PR adds padding in the large breakpoint:

Add padding for suggested articles in large breakpoint

---

app/Http/Controllers/Articles/ArticlesController.php

Fix trending articles shows current article

---

app/Http/Controllers/Auth/RegisterController.php
app/Http/Requests/RegisterRequest.php
app/Rules/UniqueGitHubUser.php
resources/lang/en/errors.php
tests/Feature/AuthTest.php

- This PR attempts to check the create method of the RegisterController to see if the user already exists. If positive, we present them with a view that says: We already found a user with the given GitHub account (link to it). Would you like to login instead? and then we sent them to the login page.
Resolves #775

Handle duplicate GitHub ID upon registration

---

package-lock.json
package.json
resources/css/buttons.css
resources/views/admin/articles.blade.php
resources/views/admin/partials/_navigation.blade.php
resources/views/admin/users.blade.php
resources/views/articles/overview.blade.php
resources/views/articles/show.blade.php
resources/views/components/articles/form.blade.php
resources/views/components/articles/summary.blade.php
resources/views/components/community-member.blade.php
resources/views/components/threads/form.blade.php
resources/views/forum/_thread.blade.php
resources/views/forum/overview.blade.php
resources/views/forum/threads/show.blade.php
resources/views/home.blade.php
resources/views/layouts/_ads/_banner.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_nav.blade.php
resources/views/users/articles.blade.php
resources/views/users/settings/profile.blade.php
tailwind.config.js

Resolves #777 
Big thanks to @faissaloux for all the hard work on this PR #780. I created a new PR as I was slow reviewing this and so needed a rebase.

Upgrade tailwind to v3

---

resources/js/search.js
resources/views/_partials/_search.blade.php

This pull request resolves #787
To fix the search , I refactored the Alpine component to use an object to handle state which brings it more in line with other components such as the editor.
Doing this allowed me to fix a couple of bugs introduced since the upgrade to Alpine v3 and will make it easier to maintain moving forward.
Some queries have hundreds or thousands of matching results, but we only ever ask for the 5 most relevant so our dropdown menu doesn't get too large. As part of this PR, I am outputting the actual total number of matching results as opposed to just the total we are actually asking for.

Refactor search to use object

---

resources/css/app.css

This PR removes the border from code blocks which appeared after the upgrade to Tailwind 3.0
**Before**
**After**

Remove border from code blocks

---

app/Http/Controllers/Settings/ApiTokenController.php
app/Jobs/CreateApiToken.php
resources/lang/en/settings.php
resources/views/layouts/_alerts.blade.php
resources/views/users/settings/api_tokens.blade.php
tests/Feature/SettingsTest.php

So, as pointed out, the tokens displayed for API are actually hashes and as such, useless to show the user.
Now instead, we use the session success feature to show the user their API token once when generated, asking them to copy it. The UI has been updated to remove the hashed tokens in the settings page.

Updates API token settings to show token when first generated

---

app/Listeners/MarkLastActivity.php
tests/Feature/ReplyTest.php

Resolves #817 by disabling the update to `updated_at` when touching the `last_activity_at`

Prevent timestamp update

---

app/Http/Livewire/Editor.php
composer.lock
package-lock.json
resources/views/articles/overview.blade.php
resources/views/forum/overview.blade.php
resources/views/livewire/editor.blade.php

This PR resolves #826
Livewire should [support both](https://laravel-livewire.com/docs/2.x/properties#important-notes) `Collection` and `EloquentCollection` and it did so on previous versions, but seems to have broken the editor somewhere between `2.5.5` and `2.10.4`. The issue could be with the Livewire/Alpine integration.
Swapping the collections for arrays has solved the issue.
This PR bumps all frontend and backend dependencies within the defined version constraints of `composer.json` and `package.json`.
I also swapped the avatar in the user select for the user's full name which mirrors GitHub's editor.

Upgrade dependencies

---

resources/js/search.js
resources/views/_partials/_search.blade.php
resources/views/layouts/_nav.blade.php
resources/views/layouts/base.blade.php

Hi Dries. This resolves [#834](https://github.com/laravelio/laravel.io/issues/834)
Fyi, search on mobile is broken on the live version.
I'd ditch the articles/threads snippets and I'd leave only the titles. What do you think about it?

Convert search to command palette

---

app/Models/Article.php
config/feed.php
resources/views/articles/overview.blade.php
resources/views/forum/overview.blade.php

This PR resolves #654 by adding a new feed for articles and adding a new `RSS Feed` link to the articles overview.
As part of this, I also noticed the `RSS Feed` link on the forum was not working as the href was not set so I updated this too.
We already have `@include('feed::links')` in `base.blade.php` so the feed is automatically added to the source of the page.
Below is an example of the generated feed.

Add RSS feed for articles

---

app/Models/Article.php

I checked the RSS feed and I noticed that the urls of the articles were not pointing to the actual article.
As you can see in the example below, the URL to the article is passed as an URL query.
This is caused by using the wrong route name. When using the `articles.show` route, the URL becomes `https://laravel.io/articles/an-unopinionated-package-to-make-laravel-apps-tenant-aware` which is an actual page.
```xml
<entry>
<title>
<![CDATA[ An unopinionated package to make Laravel apps tenant aware ]]>
</title>
<link rel="alternate" href="https://laravel.io/articles?an-unopinionated-package-to-make-laravel-apps-tenant-aware"/>
<id>https://laravel.io/3</id>
...
</entry>
```
In addition, I also saw that non-published articles showed up in the feed, which leads to a 404 page.

Use articles.show route to get correct url and only show published articles

---

app/Http/Requests/UpdateProfileRequest.php
app/Jobs/UpdateProfile.php
app/Models/User.php
database/factories/UserFactory.php
database/migrations/2022_07_29_135113_add__website_to_users_table.php
resources/views/users/profile.blade.php
resources/views/users/settings/profile.blade.php
tests/Feature/SettingsTest.php
tests/Integration/Jobs/UpdateProfileTest.php

Users can add/update their website

---

app/Models/User.php
tests/Feature/BlockUsersTest.php
tests/Integration/Jobs/BlockUserTest.php
tests/Integration/Jobs/UnblockUserTest.php

Block Users feature tests

---

app/Console/Commands/UpdateArticleViewCounts.php
resources/views/layouts/_fathom.blade.php
tests/Feature/CanonicalUrlTest.php
tests/Integration/Commands/UpdateArticleViewCountsTest.php

This PR ensures view counts include both laravel.io URLs and canonical URLs.
It also conditionally sets the canonical tracking in Fathom to ensure views are collected for the correct URL.

Merge article counts

---

app/Models/User.php
resources/views/forum/overview.blade.php
tests/Integration/Models/UserTest.php

Exclude author solutions from counting

---

app/Notifications/SlowQueryLogged.php
app/Providers/AppServiceProvider.php

This PR utilises Laravel's [whenQueryingForLongerThan](https://laravel.com/docs/9.x/database#monitoring-cumulative-query-time) functionality to send a Telegram message to admins if a slow query is encountered.
@driesvints do you think we should make the duration parameter of `whenQueryingForLongerThan` configurable or ship this and see how we get on?

Send a notification on slow query

---

resources/views/articles/show.blade.php

**This banner:**
**Is visible for all logged in users, but it should be only visible for the owner of the article and here is why:**
**The file is: resources/views/articles/show.blade.php**
**To fix it I added this:**
**Disclamer: I didn't test it, I just added that bit of code, the reason is that I couldn't install it on my Windows machine without Valet, but I think the code is correct.**

Show banner info only for the owner of the article

---

resources/views/_partials/_search.blade.php
resources/views/components/avatar.blade.php
resources/views/components/sponsor-logo.blade.php
resources/views/layouts/_ads/_footer.blade.php
resources/views/layouts/_ads/_forum_sidebar.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_nav.blade.php
resources/views/layouts/base.blade.php
resources/views/vendor/mail/html/message.blade.php
resources/views/vendor/mail/markdown/message.blade.php

Hello,
This is a PR that targets SEO.
Google benchmarks websites by simulating low performances devices and penalizes rankings for those that are too slow to load (laravel.io takes 3.1s on slow devices, and Google requires 2.5s nowadays).
I don't have access to your numbers, but it seems like laravel.io ranks only because of its reputation and the large amount of content on the forum (it has backlinks from laravel.com and a hell lot of high authorities).
This PR introduces a few frontend changes like adding `loading="lazy"` attributes, missing `alt` attributes values, and deferring the loading of JavaScript. These clearly are the low-hanging fruits, but they should do the trick.
- Passive higher rankings on Google over time;
- Better performances on slow devices and networks.
The scores …

Technical SEO optimizations

---

app/Listeners/NotifyUsersMentionedInReply.php
app/Models/Reply.php

Added check if a user participates in a thread, if it is the user doesn't receive mention notifications bc the user already getting reply notification. Deleted thread() method from App\Models\reply because it doesn't work since reply has morphtomany relationship with App\Models\Thread
This is a bug fix for [issue#937](https://github.com/laravelio/laravel.io/issues/937)

Fix for duplicate notifications

---

app/Http/Requests/CreateReplyRequest.php
app/Http/Requests/ThreadRequest.php
app/Http/Requests/UpdateReplyRequest.php
app/Rules/InvalidMentionRule.php
tests/Feature/ForumTest.php
tests/Feature/ReplyTest.php
tests/Unit/Rules/InvalidMentionRuleTest.php

This PR prevents users from submitting spam links which look like mentions.
It does this by validating the input to ensure it doens't contain markdown in the format `[@joedixon](https://somethingnasty.com)`.

Prevents spam by blocking links posing as mentions

---

resources/views/layouts/_nav.blade.php

Adds icons to navigation dropdown

---

app/Console/Kernel.php

Environment variables will need updating with new Twitter app credentials before this one is merged.

Enables posting of articles to Twitter

---

resources/views/articles/show.blade.php
resources/views/components/articles/engage.blade.php
resources/views/components/users/profile-block.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_nav.blade.php
resources/views/users/profile.blade.php
tailwind.config.js

Update Twitter logo to X

---

resources/views/layouts/_nav.blade.php

This PR attends to the issue #963
Changes to navbar file to add new hotkeys for open search bar. Tested only on Linux. Please make sure this also works on MacOs.

Added cmd+k / ctrl+k hotkeys for search function.

---

app/Http/Controllers/Auth/GithubController.php
app/Social/GithubUser.php
lang/en/errors.php
tests/Unit/Social/GithubUserTest.php

Addresses #967
Not sure if there's more that's needed, but assuming Socialite passes all data returned from the GH api, this **should** just work.

Add repositories check to help stop spam accounts

---

resources/views/articles/show.blade.php

Without a horizontal gap the author bio runs up against their social media links. I also tightened the gap between the social links to match the spacing hierarchy between the author bio and avatar.

Fix author info spacing

---

resources/views/layouts/_nav.blade.php

fixes #962 
Moved the social icons out of the community dropdown and added them near the search icon, refer screenshot.
##Steps to reproduce
- open the home page and notice the navigation bar.

moved the github and twitter icon out of community and to nav bar

---

app/Livewire/EditReply.php
app/Livewire/Editor.php
app/Livewire/LikeArticle.php
app/Livewire/LikeReply.php
app/Livewire/LikeThread.php
app/Livewire/NotificationIndicator.php
app/Livewire/Notifications.php
composer.json
composer.lock
package-lock.json
package.json
resources/js/app.js
resources/js/editor.js
resources/views/components/threads/form.blade.php
resources/views/forum/threads/show.blade.php
resources/views/livewire/edit-reply.blade.php
resources/views/livewire/editor.blade.php
tests/Feature/EditorTest.php
tests/Feature/ForumTest.php
tests/Feature/NavigationTest.php
tests/Feature/NotificationsTest.php
tests/Feature/ReplyTest.php

This PR upgrades Livewire to v3.
I used the Livewire automated upgrade tool for the most part. However, due to some of the changes with the way events work, some of the functionality of the editor needed adapting.
`emitUp` no longer exists and so it was no longer possible to just pass the `submit` event up to the parent. In the case of a forum thread with a lot of replies, this resulted in all of the replies being updated when a reply was edited. Not ideal.
I've updated this to rely on the event Alpine was already dispatching, listening for this on the parent and stopping propagation of events. It seems to work nicely, but would appreciate an extra set of eyes.
The event is dispatched [here](https://github.com/laravelio/laravel.io/pull/961/files#diff-b80bd4d6372003621d727bb836f302ec5194189 …

Upgrades Livewire v3

---

app/Concerns/HasLikes.php
app/Livewire/Like.php
app/Livewire/LikeArticle.php
resources/views/components/articles/overview-summary.blade.php
resources/views/components/articles/user-summary.blade.php
resources/views/components/threads/overview-summary.blade.php
resources/views/components/tooltip.blade.php
resources/views/components/users/reply.blade.php
resources/views/livewire/like-article.blade.php
resources/views/livewire/like-reply.blade.php
resources/views/livewire/like-thread.blade.php
resources/views/livewire/like.blade.php

Show usernames when hovering over like icon

---

resources/views/articles/overview.blade.php
resources/views/forum/overview.blade.php

Apart of truncate I had to add flex-1 and min-w-0 to parent tag to avoid change the size of the avatar.
The same fix on "top authors list". 
closes #1040

fix: community layout

---

resources/views/layouts/_footer.blade.php

I can open an issue if needed, but noticed that the social links in the footer wrap on only the large breakpoint. It is consistently reproducible across Chrome, Safari, and Firefox. This PR fixes that behavior and makes the icon spacing consistent with community links.

Social footer links wrap unexpectedly

---

resources/views/articles/show.blade.php

This PR removes the unnecessary `<x-buk-markdown>` component which causes code formatting issues (duplicate formatting).

Removes unnecessary markdown component

---

resources/views/livewire/notifications.blade.php

Better empty state page for notifications #1044. Pretty basic, wasn't sure if we should add some forward paths as well? Let me know what you think! Open to suggestions/changes 😉

Update empty notifications display

---

tests/Feature/ReplyTest.php

In PR https://github.com/laravelio/laravel.io/pull/1072 `->only()` was introduced in the `Feature/ReplyTest.php` test file. https://github.com/laravelio/laravel.io/blob/23272f486d068420e07fcfcb8b38b6427eb78e89/tests/Feature/ReplyTest.php#L218
This means only that particular test runs and others are ignored. This PR fixes that.

Allow all tests to run in the suite

---

resources/views/articles/show.blade.php
resources/views/users/profile.blade.php

Issue https://github.com/laravelio/laravel.io/issues/1122

UPDATE - Header in articles.show and users.profile view to be boxed

---

phpunit.xml
tests/Feature/ConfigTest.php

This PR helps #986 
Improve tests speed
**Before:**
**After:**
About 1/3 faster on my machine

Speed up tests by using lower bcrypt rounds in testing env #986

---

README.md
app/Console/Commands/PostArticleToTwitter.php
composer.json
composer.lock
resources/views/articles/overview.blade.php
resources/views/articles/show.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/components/articles/engage.blade.php
resources/views/components/articles/form.blade.php
resources/views/components/threads/form.blade.php
resources/views/components/users/profile-block.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_nav.blade.php
resources/views/users/articles.blade.php
resources/views/users/profile.blade.php
resources/views/users/settings/api_tokens.blade.php
resources/views/users/settings/profile.blade.php
tests/Feature/ArticleTest.php

REFACTOR - Twitter to X (Twitter) and twitter.com to x.com

---

app/Providers/Filament/AdminPanelProvider.php

[Ah one thing I notice now in production: a link to get back to the main website in the nav somewhere would be great.](https://github.com/laravelio/laravel.io/pull/1344#issuecomment-3312532911)
We already have the `Dashboard` link that takes us to _/admin_, so I think it's a good idea and makes sense to let the logo take us to main website

Set "/" as the URL for the logo in the admin panel
