database/migrations/2013_09_23_111349_add_description_field_to_tags.php

Description field now nullable

---

resources/assets/sass/_forum.scss
resources/assets/sass/app.scss

add max-width for all images inside `panel-body`, fixes #242

add max width for images inside panel-body

---

app/User.php

Latest threads on user profiles is in wrong sequence #256 fix

latest thread query issue with order fixed

---

app/Http/Controllers/Auth/GithubController.php
app/Jobs/UpdateProfile.php

Updates users GitHub username whenever they login using social authentication

---

resources/views/forum/threads/edit.blade.php
resources/views/forum/threads/show.blade.php

- Fixes #280 
- Open to improving or scrapping this if you guys don't like it.

If applied, this commit adds the link to forum rules on thread edit page and below the reply box

---

package.json
resources/assets/js/bootstrap.js
resources/assets/sass/app.scss
yarn.lock

I've included the following components:
* json
* css
* javascript
* less
* sass
* php
Do we need more?

add prismjs, fixes #260

---

resources/assets/sass/_forum.scss

Fixes [#302](https://github.com/laravelio/portal/issues/301)

Fix Text doesn't breaks in thread box bug

---

resources/views/forum/threads/show.blade.php

move the delete modal outside of the reply panel

---

app/User.php
database/factories/UserFactory.php
database/migrations/2017_08_29_123258_add_banned_at_column.php
tests/Feature/AdminTest.php
tests/Feature/AuthTest.php

migrate is_banned field with updated_at value to banned_at column
fixes #265

add banned_at column

---

resources/assets/sass/_nav.scss
resources/views/layouts/_nav.blade.php

add user dropdown icons

---

app/Http/Controllers/ProfileController.php
app/User.php
composer.json
composer.lock
resources/assets/sass/_forum.scss
routes/web.php

adds an avatar route that generates a png with the users name initials.
for local testing you need to copy the d parameter url into a new tab. localhost urls are not used by gravatar.
Fixes #264

add avatar route with name initials

---

license.txt

Update license year

---

resources/assets/sass/_profile.scss
resources/views/users/_user_info.blade.php

clip long usernames and render an ellipsis at the end
fixes #346

Add ellipsis text overflow for username

---

app/Http/Requests/CreateReplyRequest.php
app/Http/Requests/ThreadRequest.php
app/Http/Requests/UpdatePasswordRequest.php
app/Http/Requests/UpdateReplyRequest.php
app/Rules/DoesNotContainUrlRule.php
app/Rules/HttpImageRule.php
app/Rules/PasscheckRule.php
spec/Rules/DoesNotContainUrlRuleSpec.php
spec/Rules/HttpImageRuleSpec.php
tests/Components/Rules/PasscheckRuleTest.php

#357 Changed Folder from Validation to Rules, changed the tests and spec directory as well. and modified the Request files.

Changed Validation to Rules and changed affected places

---

app/Http/Controllers/Auth/EmailConfirmationController.php
app/Http/Controllers/Auth/RegisterController.php

Ref: https://github.com/laravelio/portal/issues/359

Replace dispatchNow with dispatch where applicable.

---

package-lock.json
package.json
resources/css/app.css
resources/js/bootstrap.js
webpack.mix.js

I've pulled in tailwind and have it building with mix. I've also removed `bootstrap-sass` and `bootswatch` which I don't think will be needed anymore.
However, there are a load of dependencies which I don't think at first glance are being used:
- `axios`
- `vue`
- `vue-resource`
Do you know if they are being used somewhere I've not spotted?

Setup tailwind

---

resources/css/app.css
resources/js/app.js
resources/views/layouts/_nav.blade.php
tailwind.config.js

Implement navbar

---

resources/css/app.css
resources/views/layouts/_ads/_footer.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_sponsors.blade.php
resources/views/layouts/base.blade.php

Implement footer

---

resources/css/app.css
resources/views/forum/overview.blade.php
resources/views/forum/threads/info/avatar.blade.php
resources/views/forum/threads/info/tags.blade.php
resources/views/layouts/_footer.blade.php
resources/views/layouts/_nav.blade.php
resources/views/layouts/default.blade.php
tailwind.config.js

This PR tries to match as close as possible the layout highlighted in the Refactoring UI [post on Medium](https://medium.com/refactoring-ui/redesigning-laravel-io-c47ac495dff0).
I've taken a pragmatic approach to things like spacing where I have used a sensible tailwind default value rather than trying to exactly match all of the spacing outlined in the article.
I have had a first stab at producing a grayscale as per the article, but some of them were not explicitly stated so I have had a first pass, but welcome to feedback.
I have not yet tackled pagination.
Let me know what you think!

Forum overview

---

resources/css/app.css
resources/views/layouts/_nav.blade.php

I wasn't logged in when building the nav initially. When I logged in, there were some styles missing

fix logged in nav

---

resources/css/app.css
resources/views/auth/login.blade.php
resources/views/layouts/small.blade.php

Style login page

---

resources/css/app.css
resources/views/auth/register.blade.php
resources/views/privacy.blade.php
resources/views/rules.blade.php
resources/views/terms.blade.php

Style legal pages

---

app/Http/Controllers/Forum/ThreadsController.php
package-lock.json
package.json
resources/css/app.css
resources/js/app.js
resources/js/components/MultiSelect.vue
resources/views/forum/threads/_form.blade.php
resources/views/forum/threads/create.blade.php

Couple of things to note on this.
I put the title below the nav along with the search box to bring it inline with the forum overview page. I thought this worked well given the note at the top of the page about using search before posting.
I'm not a huge fan of the notification at the top, but I think I will change this when I style all notifications across the app.

Style create thread page

---

resources/views/forum/threads/show.blade.php
resources/views/replies/edit.blade.php

Edit replies

---

app/Http/Controllers/Forum/ThreadsController.php
resources/views/forum/threads/_form.blade.php
resources/views/forum/threads/edit.blade.php

Style edit thread page

---

resources/css/app.css
resources/views/layouts/settings.blade.php
resources/views/users/settings/password.blade.php
resources/views/users/settings/profile.blade.php

Settings profile and password pages

---

resources/css/app.css
resources/views/forum/threads/show.blade.php

Add syntax highlighting to thread

---

resources/css/app.css
resources/css/pagination.css
resources/views/admin/overview.blade.php
resources/views/forum/overview.blade.php

Only thing to note on this is I split the pagination styles into their own CSS file. I plan to split the main `resources/app.css` file different files to keep things organised so this is the start of that process.

Style pagination

---

resources/css/app.css
resources/css/tables.css
resources/views/admin/overview.blade.php
resources/views/admin/users/show.blade.php

Style admin area

---

resources/css/alerts.css
resources/css/app.css
resources/js/app.js
resources/views/forum/overview.blade.php
resources/views/forum/threads/create.blade.php
resources/views/forum/threads/edit.blade.php
resources/views/layouts/_alerts.blade.php
resources/views/layouts/default.blade.php
resources/views/layouts/settings.blade.php
resources/views/replies/edit.blade.php

Style notifications

---

resources/views/forum/threads/show.blade.php

Move BSA ad

---

resources/views/forum/threads/show.blade.php

Add breadcrumb to forum thread

---

resources/views/layouts/_ads/_footer.blade.php
resources/views/layouts/_ads/_forum_sidebar.blade.php

The dark banners perform not as good as expected and so I've changed them to the light ones for the end of the test period.

change flare banners to light versions

---

package-lock.json
package.json
resources/css/threads.css
resources/js/app.js
resources/js/components/Editor.vue
resources/views/forum/threads/_form.blade.php
resources/views/forum/threads/show.blade.php
resources/views/replies/edit.blade.php
tests/Feature/ForumTest.php
tests/Feature/ReplyTest.php

Custom markdown editor

---

config/database.php
resources/css/nav.css
resources/views/layouts/_nav.blade.php

Fix pagination

---

resources/views/layouts/small.blade.php

Adjust login width on xl screens

---

resources/views/forum/threads/show.blade.php

Style old thread notice

---

app/Helpers/HasSlug.php
tests/Integration/Models/ThreadTest.php

Fallback to default slug

---

app/Http/Livewire/NotificationCount.php
app/Http/Livewire/NotificationIndicator.php
app/Http/Livewire/Notifications.php
app/Notifications/NewReplyNotification.php
app/Policies/NotificationPolicy.php
app/Providers/AuthServiceProvider.php
composer.lock
database/migrations/2020_01_09_193921_create_notifications_table.php
resources/css/custom.css
resources/views/layouts/_nav.blade.php
resources/views/livewire/notification-count.blade.php
resources/views/livewire/notification_count.blade.php
resources/views/livewire/notification_indicator.blade.php
resources/views/livewire/notifications.blade.php
resources/views/users/_latest_replies.blade.php
resources/views/users/_latest_threads.blade.php
resources/views/users/dashboard.blade.php
resources/views/users/notifications/reply.blade.php
resources/views/users/profile.blade.php
tests/Feature/DashboardTest.php
tests/Feature/NavTest.php

This PR adds support for notifications. At the moment, it only works for new replies, but it sets the foundation to easily add new ones.
It uses Livewire for pagination and also for the notification counter.

Add notifications to the dashboard

---

resources/views/forum/threads/show.blade.php

This PR should close #413 . It's a very simple label / link that goes to the solution if there is one present. See screenshot:
Happy to make any styling changes, but I think this is pretty neat to have on the forum.

Added button to scroll to solution

---

resources/views/_partials/_search.blade.php

Update word break

---

resources/views/layouts/_nav.blade.php

Hide dropdown on load and add missing links on mobile

---

app/Models/Article.php
resources/js/editor.js
resources/views/articles/_series_nav.blade.php
resources/views/articles/show.blade.php
tests/Feature/ArticleTest.php
tests/Integration/Models/ArticleTest.php

Add series navigation

---

app/Http/Controllers/Articles/AuthoredArticles.php
app/Http/Controllers/Articles/MyArticles.php
app/User.php
resources/views/articles/_series_nav.blade.php
resources/views/articles/show.blade.php
resources/views/layouts/_nav.blade.php
resources/views/livewire/show-articles.blade.php
resources/views/users/_latest_articles.blade.php
resources/views/users/_latest_replies.blade.php
resources/views/users/_latest_threads.blade.php
resources/views/users/_metrics.blade.php
resources/views/users/articles.blade.php
resources/views/users/dashboard.blade.php
routes/web.php
tests/Feature/ArticleTest.php

Allow users to manage their articles

---

resources/views/forum/overview.blade.php

Add line breaks on forum overview

---

composer.json
composer.lock
resources/helpers.php
resources/views/forum/threads/show.blade.php
tests/Feature/ForumTest.php

https://github.com/laravelio/laravel.io/issues/529

Auto link URLs in threads and replies

---

app/Http/Livewire/ShowArticles.php
composer.json
composer.lock
package-lock.json
package.json
tests/Feature/DashboardTest.php
tests/Feature/SettingsTest.php

Bump livewire and alpine

---

resources/views/layouts/_nav.blade.php

#598 Notifications icon in nav has incorrect hover state

---

.github/workflows/enlightn.yml

I reverted the bump in Enlightn Pro, so no changes needed here.

Add enlightn

---

app/Http/Controllers/Forum/TagsController.php
app/Http/Controllers/Forum/ThreadsController.php
app/Models/User.php
resources/views/forum/overview.blade.php

Reverts laravelio/laravel.io#614

Revert "Add community section"

---

app/Http/Controllers/Forum/TagsController.php
app/Http/Controllers/Forum/ThreadsController.php
app/Models/Reply.php
app/Models/User.php
resources/views/forum/overview.blade.php

Hey @driesvints 👋 
I implemented the `countSolutions` method in eloquent by defining a new `solutionTo` relationship on the `Reply` model which maps the reply to the thread via the `solution_reply_id` on the threads table.
I _think_ this should solve the speed issue, but it's hard to know for sure until we run it against prod.
Let me know what you think!

Add community section

---

resources/views/components/threads/overview-summary.blade.php
resources/views/components/threads/summary.blade.php
resources/views/forum/overview.blade.php

Forum overview tidy

---

resources/views/components/buttons/secondary-button.blade.php
resources/views/components/buttons/secondary-cta.blade.php
resources/views/components/tag-filter.blade.php
resources/views/forum/overview.blade.php
resources/views/layouts/base.blade.php

https://user-images.githubusercontent.com/3438564/125683755-884a0854-e505-4fc9-bccb-563e0fbb5cc6.mov

Add tag filter to forum overview

---

app/Markdown/LeagueConverter.php
app/Markdown/MarkdownServiceProvider.php
composer.json
composer.lock

This change will link mentioned users in markdown across the site to their profile page.

Link mentioned users

---

database/migrations/2021_07_31_183222_unique_github_ids.php
database/schema/mysql-schema.dump

Closes https://github.com/laravelio/laravel.io/issues/363﻿

Unique GitHub ID's

---

tailwind.config.js

Style inline code

---

resources/views/articles/show.blade.php
resources/views/components/articles/overview-summary.blade.php
resources/views/components/moderators.blade.php
resources/views/components/stat-popout.blade.php
resources/views/components/threads/overview-summary.blade.php
resources/views/components/threads/reply.blade.php
resources/views/components/threads/summary.blade.php
resources/views/components/threads/thread.blade.php
resources/views/components/users/profile-block.blade.php
resources/views/emails/new_reply.blade.php
resources/views/forum/overview.blade.php
resources/views/layouts/_nav.blade.php
resources/views/users/_latest_replies.blade.php
resources/views/users/_latest_threads.blade.php
resources/views/users/_user_info.blade.php
resources/views/users/profile.blade.php

Add consistent use of username

---

resources/views/layouts/_nav.blade.php

twitter link

---

resources/views/layouts/_nav.blade.php

This PR fix nav links that was limited only on link text and not the whole tab

Fix nav links

---

resources/views/admin/partials/_navigation.blade.php

fix: admin search padding

---

app/Http/Controllers/Admin/UsersController.php

fix: class SearchUsers not found

---

app/Http/Controllers/Articles/ArticlesController.php
app/Models/User.php
resources/views/articles/index.blade.php

Top authors widget

---

app/Http/Controllers/Articles/ArticlesController.php
app/Http/Controllers/Forum/ThreadsController.php

cache top X queries

---

resources/views/components/articles/form.blade.php

remove 'show advanced options' toggle

---

resources/views/articles/show.blade.php

update decline article modal body

---

resources/views/components/articles/actions.blade.php

fix control buttons height

---

resources/views/articles/_form.blade.php
resources/views/components/articles/form.blade.php

fix save/submit dropdown width

---

resources/views/components/cta-banner.blade.php
resources/views/forum/threads/show.blade.php
webpack.mix.js

mark solution cta banner

---

resources/views/components/articles/actions.blade.php
resources/views/components/articles/filter.blade.php

Modals were not triggering on the show article page. Refactored to use the event rather than relying on parent state.

Fix modals

---

resources/views/articles/show.blade.php

hide declined articles actions for admin

---

resources/views/admin/articles.blade.php
resources/views/admin/partials/_navigation.blade.php
resources/views/admin/users.blade.php
routes/web.php
tests/Feature/AdminTest.php

make articles tab active by default in admin dashboard

---

resources/views/admin/articles.blade.php

admin articles list empty state

---

resources/views/components/threads/overview-summary.blade.php
resources/views/components/threads/reply.blade.php
resources/views/components/threads/thread.blade.php
resources/views/components/users/reply.blade.php

switch to relative dates

---

routes/web.php

fix notifications view bug

---

public/.well-known/security.txt

This is a follow up for #776 
See: https://securitytxt.org/ for more information about this file
I only add the email and not the wanted expires because I didn't know how long you want to have this. (And it means this need to be updated once in a while)

Add a .well-known/security.txt

---

resources/views/_partials/_search.blade.php

Use window.search instead of search (#784)

---

resources/views/components/articles/actions.blade.php
resources/views/components/articles/article-menu.blade.php
resources/views/components/articles/overview-summary.blade.php
resources/views/components/primary-info-panel.blade.php
resources/views/forum/threads/show.blade.php
resources/views/users/articles.blade.php

Update articles page design

---

resources/css/buttons.css

Fix delete button background

---

resources/views/components/articles/actions.blade.php

Fix actions buttons / headers space

---

app/Http/Controllers/Admin/ArticlesController.php
resources/views/articles/show.blade.php

Persist article declined banner

---

resources/views/components/threads/reply.blade.php

Add link to thread replies

---

resources/views/components/threads/reply.blade.php

Add hover state to thread replies link

---

resources/views/layouts/_fathom.blade.php

Replace condition with environment directive

---

app/Http/Controllers/Articles/ArticlesController.php
app/Models/Tag.php
database/seeders/UserSeeder.php
resources/views/components/articles/form.blade.php

Allow only admins to label special tags

---

resources/views/articles/show.blade.php
resources/views/components/articles/overview-summary.blade.php
resources/views/components/light-tag.blade.php

Make article detail page labels clickable

---

app/Policies/ArticlePolicy.php
package-lock.json
resources/views/articles/edit.blade.php
resources/views/articles/show.blade.php
resources/views/components/articles/actions.blade.php
resources/views/components/articles/form.blade.php
resources/views/components/info-banner.blade.php

prevent users edit published articles

---

resources/views/articles/overview.blade.php
resources/views/forum/overview.blade.php

Fix tag filter overflow

---

app/Console/Commands/PopulateAllUuids.php
app/Jobs/PopulateArticleUuid.php
app/Jobs/PopulateReplyUuid.php
app/Jobs/PopulateThreadUuid.php

Adds the command for #861.
I've tried following the style of the other jobs.

Populate all UUID's

---

app/Console/Commands/PopulateAllUuids.php
app/Jobs/PopulateArticleUuid.php
app/Jobs/PopulateReplyUuid.php
app/Jobs/PopulateThreadUuid.php

Fixes some problems with #864.
I've switched from Eloquent to Query Builder, because I believe it provides these benefits:
- It's a little faster.
- We don't need to serialize and store a Model in each job.
- No events will be generated (so the Scout index won't be updated).

Populate all UUID's no. 2

---

composer.json
composer.lock
resources/views/layouts/_nav.blade.php
tailwind.config.js

This PR is associated with #863.

Add icons under the chat and community dropdown

---

README.md
app/Http/Controllers/Admin/UsersController.php
database/seeders/UserSeeder.php
resources/views/admin/users.blade.php
resources/views/users/profile.blade.php
tests/Feature/AdminTest.php
tests/Feature/ProfileTest.php

Referencing issue at #875. If there is anything I should know, please let me know.

Move delete user button to Admin's users overview.

---

app/Http/Livewire/Notifications.php
resources/views/livewire/notifications.blade.php

Hello 👋🏻 
I have noticed this bug when I tried to remove all notifications one by one from 2nd page 🤔 so I tried to fix it.
https://user-images.githubusercontent.com/60013703/175752621-b0735e79-0c7b-4b7b-b827-b2d5f7480fe2.mp4
https://user-images.githubusercontent.com/60013703/175750721-19992bae-b0c9-402a-9ee0-7f7afe235aac.mp4

Fix remove notifications pagination

---

resources/views/forum/threads/create.blade.php
resources/views/forum/threads/edit.blade.php
routes/web.php

Add pastebin tip to create and edit thread pages

---

resources/css/app.css
resources/views/layouts/base.blade.php

resolves https://github.com/laravelio/laravel.io/issues/899

Remove the use of an external css file

---

database/factories/ArticleFactory.php
database/seeders/UserSeeder.php
resources/views/components/articles/overview-summary.blade.php
resources/views/users/articles.blade.php

resolves #911
following broken #912

show authored articles views count

---

resources/views/articles/show.blade.php
resources/views/components/users/profile-block.blade.php

Helloo 👋🏻 
In this PR I have added website link to articles/threads author profile

add website link to article and thread author profile

---

composer.json
composer.lock
resources/views/admin/partials/_navigation.blade.php
resources/views/articles/overview.blade.php
resources/views/components/api-token.blade.php
resources/views/components/articles/actions.blade.php
resources/views/components/articles/article-menu.blade.php
resources/views/components/articles/overview-summary.blade.php
resources/views/components/articles/user-summary.blade.php
resources/views/components/forms/editor/controls.blade.php
resources/views/components/tag-filter.blade.php
resources/views/components/threads/overview-summary.blade.php
resources/views/components/threads/reply-menu.blade.php
resources/views/components/threads/reply.blade.php
resources/views/components/threads/subscribe.blade.php
resources/views/components/threads/thread-menu.blade.php
resources/views/components/users/reply.blade.php
resources/views/forum/overview.blade.php
resources/views/forum/threads/show.blade.php
resources/views/home.blade.php
resources/views/layouts/_nav.blade.php
resources/views/livewire/like-article.blade.php
resources/views/livewire/like-reply.blade.php
resources/views/livewire/like-thread.blade.php
resources/views/notifications/mention.blade.php
resources/views/notifications/new_reply.blade.php
resources/views/users/_latest_replies.blade.php
resources/views/users/profile.blade.php
resources/views/users/settings/blocked.blade.php
resources/views/users/settings/settings.blade.php

Update from heroicons v1 to heroicons v2

---

resources/css/modal.css

Fix modals height on small screens

---

app/Models/User.php

Set $table with TABLE costant

---

app/Http/Controllers/Settings/ApiTokenController.php
app/Jobs/CreateApiToken.php

This PR fix this issue https://github.com/laravelio/laravel.io/issues/959.
Below is the screenshot after fix.

fix API token not displaying after creation

---

app/Http/Controllers/HomeController.php
app/Models/User.php

Uncount banned users

---

app/Http/Controllers/SocialImageController.php
app/Jobs/GenerateSocialShareImage.php

Turn GenerateSocialShareImage Action to a Job

---

CONTRIBUTING.md
README.md
app/Http/Controllers/Auth/GitHubController.php
app/Models/User.php
app/Rules/UniqueGitHubUser.php
app/Social/GitHubUser.php
lang/en/errors.php
resources/views/errors/500.blade.php
resources/views/layouts/_nav.blade.php
routes/web.php
tests/Unit/Social/GitHubUserTest.php

Change "Github" to "GitHub"

---

tests/Integration/Models/ThreadTest.php

#986 remove sleep to improve test speed

---

resources/views/components/articles/overview-summary.blade.php

Based on issue : #1215
@driesvints Let me know if there's anything specific you'd like me to address or improve.

Corrected image source error in article's overview summary component
